In [92]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [93]:
##Load the Dataset:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [94]:
##Preprocess the data:
##Dropping The Irelevent Data:
data=data.drop(["RowNumber","CustomerId","Surname"],axis=1)
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [95]:
data["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [96]:
data["Gender"].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [97]:
##Encode categorical variables:
label_encoder_gender=LabelEncoder()
data["Gender"]=label_encoder_gender.fit_transform(data["Gender"])
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France       0  ...               1        101348.88       1
1          608     Spain       0  ...               1        112542.58       0
2          502    France       0  ...               0        113931.57       1
3          699    France       0  ...               0         93826.63       0
4          850     Spain       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [98]:
onehot_encoder_geo=OneHotEncoder()
geo_encoded_value=onehot_encoder_geo.fit_transform(data[["Geography"]])
geo_encoded_value

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [99]:
geo_encoded_df=pd.DataFrame(geo_encoded_value.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [100]:
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [101]:
##Combine this to orginal dataframe:
data=pd.concat([data.drop("Geography",axis=1),geo_encoded_df],axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [102]:
##Save the Encoder:
with open("label_encoder_gender.pkl","wb") as file:
    pickle.dump(label_encoder_gender,file)

with open("onehot_encoder_geo.pkl","wb") as file:
    pickle.dump(onehot_encoder_geo,file)

In [103]:
##Divide The Dataset:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [115]:
X=data.drop('Exited',axis=1)
y=data['Exited']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

##Sacling the data:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [116]:
with open("scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

### ANN Implementation

In [117]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

In [118]:
##BUILD OUR ANN MODEL
model = Sequential(
    [
        Dense(64, activation="relu",input_shape=(X_train.shape[1],)),
        Dense(32, activation="relu"),
        Dense(1, activation="sigmoid")
    ]
)

In [119]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 64)                832

 dense_10 (Dense)            (None, 32)                2080

 dense_11 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [120]:
import tensorflow as tf
opt=tf.keras.optimizers.Adam(learning_rate=0.01)
loss=tf.keras.losses.BinaryCrossentropy()

In [121]:
##Compile the model:
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [122]:
##Set up the Tensorboard:
import datetime
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard 
log_dir="logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [125]:
##Set up Earlystopping:
early_stooping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [140]:
##Training the Model:
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stooping_callback]
)

Epoch 1/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3318 - accuracy: 0.8649 - val_loss: 0.3498 - val_accuracy: 0.8615
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3289 - accuracy: 0.8675 - val_loss: 0.3599 - val_accuracy: 0.8555
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3263 - accuracy: 0.8664 - val_loss: 0.3528 - val_accuracy: 0.8565
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3248 - accuracy: 0.8643 - val_loss: 0.3450 - val_accuracy: 0.8535
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3238 - accuracy: 0.8696 - val_loss: 0.3437 - val_accuracy: 0.8590
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3223 - accuracy: 0.8696 - val_loss: 0.3702 - val_accuracy: 0.8485
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3199 - accuracy: 0.8691 - val_loss: 0.3630 - val_accuracy: 0.8545
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3201 - accuracy: 0.8694 - val_loss: 0.3441 - val_accuracy: 0.8660
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3202 - accuracy: 0.8654 - val_loss: 0.3462 - val_accuracy: 0.8595
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3135 - accuracy: 0.8717 - val_loss: 0.3507 - val_accuracy: 0.8580
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3115 - accuracy: 0.8730 - val_loss: 0.3528 - val_accuracy: 0.8615
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3134 - accuracy: 0.8691 - val_loss: 0.3553 - val_accuracy: 0.8590
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3081 - accuracy: 0.8725 - val_loss: 0.3451 - val_accuracy: 0.8650
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3103 - accuracy: 0.8735 - val_loss: 0.3714 - val_accuracy: 0.8520
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3023 - accuracy: 0.8734 - val_loss: 0.3627 - val_accuracy: 0.8535

In [141]:
model.save('model.h5')

d:\Final_Projects\Churn_Prediction\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(